openapi: 3.0.3
info:
  title: FD Challenge
  contact:
    email: rafael.lott2@gmail.com
  version: 1.0.11
servers:
  - url: http://localhost:8080

paths:
  /todos:
    get:
      summary: Retrieve the filtered Todos
      tags:
        - Todos
      operationId: adapters.endpoints.todos.get_todos
      parameters:
        - in: query
          name: completed
          schema:
            type: boolean
          description: Filter if the job was completed
        - in: query
          name: title
          schema:
            type: string
          description: Filter the title
        - in: query
          name: qtd_items
          schema:
            type: integer
            default: 5
          description: The max element returned. Maximum value is 20 items
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodosReturn'
        '400':
          description: Invalid status value
        '401':
          description: Unauthorized user
        '405':
          description: Method not allowed

components:
  schemas:
    TodosReturn:
      type: object
      properties:
        id:
          type: integer
          example: 10
        title:
          type: string
          example: Example of a title

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: adapters.gateway.security.decode_token

security:
  - bearerAuth: []
