openapi: 3.0.3
info:
  title: FD Challenge
  contact:
    email: rafael.lott2@gmail.com
  version: 1.0.11
servers:
  - url: https://localhost:8080/

paths:
  /todos:
    get:
      summary: some summary
      description: some description
      operationId: adapters.endpoints.todos.get_todos
      parameters:
        - name: completed
          in: query
          description: Status of job
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodosReturn'
        '400':
          description: Invalid status value

components:
  schemas:
    TodosReturn:
      type: object
      properties:
        id:
          type: integer
          example: 10
        title:
          type: string
          example: Example of a title

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: X-API-KEY
      in: header
      x-apikeyInfoFunc: adapters.gateway.security.authentication_process

security:
  - ApiKeyAuth: []
